# Generated by OmopViewer 0.4.0
# Be careful editing this file

server <- function(input, output, session) {
  # download raw data -----
  output$download_raw <- shiny::downloadHandler(
    filename = "results.csv",
    content = function(file) {
      data |>
        omopgenerics::bind() |>
        omopgenerics::exportSummarisedResult(fileName = file)
    }
  )
  # update buttons ----
  updateButtons <- shiny::reactiveValues(
    summarise_omop_snapshot = FALSE,
    summarise_observation_period = FALSE,
    summarise_clinical_records = FALSE,
    summarise_concept_id_counts = FALSE,
    summarise_characteristics = FALSE
  )

  # summarise_omop_snapshot -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_omop_snapshot <- TRUE
  }) |> shiny::bindEvent(input$summarise_omop_snapshot_cdm_name,
    input$summarise_omop_snapshot_variable_name,
    ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$summarise_omop_snapshot, {
    if (updateButtons$summarise_omop_snapshot == TRUE) {
      output$update_message_summarise_omop_snapshot <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_omop_snapshot <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_omop_snapshot, {
    updateButtons$summarise_omop_snapshot <- FALSE
  })

  ## get summarise_omop_snapshot data
  getSummariseOmopSnapshotData <- shiny::eventReactive(input$update_summarise_omop_snapshot, {
    data[["summarise_omop_snapshot"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_omop_snapshot_cdm_name,
        .data$variable_name %in% input$summarise_omop_snapshot_variable_name
      )
  })
  getSummariseOmopSnapshotTable <- shiny::reactive({
    getSummariseOmopSnapshotData() |>
      OmopSketch::tableOmopSnapshot()
  })
  output$summarise_omop_snapshot_table <- gt::render_gt({
    getSummariseOmopSnapshotTable()
  })
  output$summarise_omop_snapshot_table_download <- shiny::downloadHandler(
    filename = paste0("table_snapshot.", input$summarise_omop_snapshot_table_format),
    content = function(file) {
      gt::gtsave(getSummariseOmopSnapshotTable(), file)
    }
  )
  # summarise_observation_period -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_observation_period <- TRUE
  }) |> shiny::bindEvent(input$summarise_observation_period_cdm_name,
    input$summarise_observation_period_observation_period_ordinal,
    input$summarise_observation_period_variable_name,
    input$summarise_observation_period_estimate_name,
    ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$summarise_observation_period, {
    if (updateButtons$summarise_observation_period == TRUE) {
      output$update_message_summarise_observation_period <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_observation_period <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_observation_period, {
    updateButtons$summarise_observation_period <- FALSE
  })

  ## get summarise_observation_period data
  getSummariseObservationPeriodData <- shiny::eventReactive(input$update_summarise_observation_period, {
    data[["summarise_observation_period"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_observation_period_cdm_name,
        .data$variable_name %in% input$summarise_observation_period_variable_name,
        .data$estimate_name %in% input$summarise_observation_period_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$observation_period_ordinal %in% input$summarise_observation_period_observation_period_ordinal)
  })
  getSummariseObservationPeriodTable <- shiny::reactive({
    getSummariseObservationPeriodData() |>
      dplyr::filter(!(grepl("na", .data$estimate_name) | grepl("zero", .data$estimate_name))) |>
      OmopSketch::tableObservationPeriod()
  })
  output$summarise_observation_period_table <- gt::render_gt({
    getSummariseObservationPeriodTable()
  })
  output$summarise_observation_period_table_download <- shiny::downloadHandler(
    filename = paste0("table_obsevation_period.", input$summarise_observation_period_table_format),
    content = function(file) {
      gt::gtsave(getSummariseObservationPeriodTable(), file)
    }
  )
  getSummariseObservationPeriodPlot <- shiny::reactive({
    getSummariseObservationPeriodData() |>
      OmopSketch::plotObservationPeriod(
        variableName = input$summarise_observation_period_plot_variable,
        plotType = input$summarise_observation_period_plot_plot_type,
        facet = input$summarise_observation_period_plot_facet,
        colour = input$summarise_observation_period_plot_colour
      )
  })
  output$summarise_observation_period_plot <- shiny::renderUI({
    x <- getSummariseObservationPeriodPlot()
    renderInteractivePlot(x, input$summarise_observation_period_plot_interactive)
  })
  output$summarise_observation_period_plot_download <- shiny::downloadHandler(
    filename = "plot_observation_period.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseObservationPeriodPlot(),
        width = as.numeric(input$summarise_observation_period_plot_width),
        height = as.numeric(input$summarise_observation_period_plot_height),
        units = input$summarise_observation_period_plot_units,
        dpi = as.numeric(input$summarise_observation_period_plot_dpi)
      )
    }
  )
  getSummariseObservationPeriodTableMissing <- shiny::reactive({
    getSummariseObservationPeriodData() |>
      OmopSketch::tableMissingData()
  })
  output$summarise_observation_period_tableMissing <- gt::render_gt({
    getSummariseObservationPeriodTableMissing()
  })
  output$summarise_observation_period_tableMissing_download <- shiny::downloadHandler(
    filename = paste0("table_missing_data_observation_period.", input$summarise_observation_period_tableMissing_format),
    content = function(file) {
      gt::gtsave(getSummariseObservationPeriodTableMissing(), file)
    }
  )
  # summarise_clinical_records -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_clinical_records <- TRUE
  }) |> shiny::bindEvent(input$summarise_clinical_records_cdm_name,
    input$summarise_clinical_records_omop_table,
    input$summarise_clinical_records_variable_name,
    input$summarise_clinical_records_estimate_name,
    ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$summarise_clinical_records, {
    if (updateButtons$summarise_clinical_records == TRUE) {
      output$update_message_summarise_clinical_records <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_clinical_records <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_clinical_records, {
    updateButtons$summarise_clinical_records <- FALSE
  })

  ## get summarise_clinical_records data
  getSummariseClinicalRecordsData <- shiny::eventReactive(input$update_summarise_clinical_records, {
    data[["summarise_clinical_records"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_clinical_records_cdm_name,
        .data$variable_name %in% input$summarise_clinical_records_variable_name,
        .data$estimate_name %in% input$summarise_clinical_records_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$omop_table %in% input$summarise_clinical_records_omop_table)
  })
  getSummariseClinicalRecordsTable <- shiny::reactive({
    getSummariseClinicalRecordsData() |>
      dplyr::filter(!(grepl("na", .data$estimate_name) | grepl("zero", .data$estimate_name))) |>
      OmopSketch::tableClinicalRecords()
  })
  output$summarise_clinical_records_table <- gt::render_gt({
    getSummariseClinicalRecordsTable()
  })
  output$summarise_clinical_records_table_download <- shiny::downloadHandler(
    filename = paste0("table_clinical_records.", input$summarise_clinical_records_table_format),
    content = function(file) {
      gt::gtsave(getSummariseClinicalRecordsTable(), file)
    }
  )
  getSummariseClinicalRecordsTableMissing <- shiny::reactive({
    getSummariseClinicalRecordsData() |>
      OmopSketch::tableMissingData()
  })
  output$summarise_clinical_records_tableMissing <- gt::render_gt({
    getSummariseClinicalRecordsTableMissing()
  })
  output$summarise_clinical_records_tableMissing_download <- shiny::downloadHandler(
    filename = paste0("table_missing_data_clinical_records.", input$summarise_clinical_records_tableMissing_format),
    content = function(file) {
      gt::gtsave(getSummariseClinicalRecordsTableMissing(), file)
    }
  )
  # summarise_concept_id_counts -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_concept_id_counts <- TRUE
  }) |> shiny::bindEvent(input$summarise_concept_id_counts_cdm_name,
    input$summarise_concept_id_counts_omop_table,
    input$summarise_concept_id_counts_estimate_name,
    ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$summarise_concept_id_counts, {
    if (updateButtons$summarise_concept_id_counts == TRUE) {
      output$update_message_summarise_concept_id_counts <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_concept_id_counts <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_concept_id_counts, {
    updateButtons$summarise_concept_id_counts <- FALSE
  })

  ## get summarise_concept_id_counts data
  getSummariseConceptIdCountsData <- shiny::eventReactive(input$update_summarise_concept_id_counts, {
    data[["summarise_concept_id_counts"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_concept_id_counts_cdm_name,
        .data$estimate_name %in% input$summarise_concept_id_counts_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$omop_table %in% input$summarise_concept_id_counts_omop_table)
  })
  getSummariseConceptIdCountsTidy <- shiny::reactive({
    getSummariseConceptIdCountsData() |>
      OmopSketch::tableConceptIdCounts(display = input$summarise_concept_id_counts_tidy_display)
  })
  output$summarise_concept_id_counts_tidy <- reactable::renderReactable({
    getSummariseConceptIdCountsTidy()
  })
  output$summarise_concept_id_counts_tidy_download <- shiny::downloadHandler(
    filename = "concept_id_counts.csv",
    content = function(file) {
      getSummariseConceptIdCountsTidy() |>
        readr::write_csv(file = file)
    }
  )
  getSummariseConceptIdCountsTable <- shiny::reactive({
    getSummariseConceptIdCountsData() |>
      OmopSketch::tableTopConceptCounts(top = as.numeric(input$summarise_concept_id_counts_table_top))
  })
  output$summarise_concept_id_counts_table <- shiny::renderUI({
    getSummariseConceptIdCountsTable()
  })
  output$summarise_concept_id_counts_table_download <- shiny::downloadHandler(
    filename = paste0("table_top_concept_counts.", input$summarise_concept_id_counts_table_format),
    content = function(file) {
      gt::gtsave(getSummariseConceptIdCountsTable(), file)
    }
  )
  # summarise_characteristics -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_characteristics <- TRUE
  }) |> shiny::bindEvent(input$summarise_characteristics_cdm_name,
    input$summarise_characteristics_cohort_name,
    input$summarise_characteristics_variable_name,
    input$summarise_characteristics_estimate_name,
    ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$summarise_characteristics, {
    if (updateButtons$summarise_characteristics == TRUE) {
      output$update_message_summarise_characteristics <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_characteristics <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_characteristics, {
    updateButtons$summarise_characteristics <- FALSE
  })

  ## get summarise_characteristics data
  getSummariseCharacteristicsData <- shiny::eventReactive(input$update_summarise_characteristics, {
    data[["summarise_characteristics"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_characteristics_cdm_name,
        .data$variable_name %in% input$summarise_characteristics_variable_name,
        .data$estimate_name %in% input$summarise_characteristics_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_characteristics_cohort_name)
  })
  getSummariseCharacteristicsTable <- shiny::reactive({
    getSummariseCharacteristicsData() |>
      CohortCharacteristics::tableCharacteristics(
        header = input$summarise_characteristics_table_header,
        groupColumn = input$summarise_characteristics_table_group_column,
        hide = input$summarise_characteristics_table_hide
      )
  })
  output$summarise_characteristics_table <- gt::render_gt({
    getSummariseCharacteristicsTable()
  })
  output$summarise_characteristics_table_download <- shiny::downloadHandler(
    filename = paste0("table_characteristics.", input$summarise_characteristics_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCharacteristicsTable(), file)
    }
  )
  getSummariseCharacteristicsPlot <- shiny::reactive({
    getSummariseCharacteristicsData() |>
      CohortCharacteristics::plotCharacteristics(
        plotType = input$summarise_characteristics_plot_plot_type,
        facet = input$summarise_characteristics_plot_facet,
        colour = input$summarise_characteristics_plot_colour
      )
  })
  output$summarise_characteristics_plot <- shiny::renderUI({
    x <- getSummariseCharacteristicsPlot()
    renderInteractivePlot(x, input$summarise_characteristics_plot_interactive)
  })
  output$summarise_characteristics_plot_download <- shiny::downloadHandler(
    filename = "plot_characteristics.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseCharacteristicsPlot(),
        width = as.numeric(input$summarise_characteristics_plot_width),
        height = as.numeric(input$summarise_characteristics_plot_height),
        units = input$summarise_characteristics_plot_units,
        dpi = as.numeric(input$summarise_characteristics_plot_dpi)
      )
    }
  )
}
