# Generated by OmopViewer 0.4.0
# Be careful editing this file

ui <- bslib::page_navbar(
  title = shiny::tags$span(
    shiny::tags$img(
      src = "logo.png",
      width = "auto",
      height = "46px",
      class = "me-3",
      alt = "logo"
    ),
    "Database characterisation"
  ),
  theme = bslib::bs_theme(brand = TRUE),
  shiny::tags$style(HTML(
    ".sticky-top-btn {
      position: sticky;
      top: 0;
      z-index: 20;
      background: var(--bs-body-bg);
    }"
  )),
  bslib::nav_panel(
    title = "Background",
    icon = shiny::icon("book-atlas"),
    backgroundCard("background.md")
  ),
  bslib::nav_panel(
    title = "Snapshot",
    icon = shiny::icon("camera"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        bslib::card(
          class = "sticky-top-btn",
          bslib::card_body(
            shiny::actionButton(
              inputId = "update_summarise_omop_snapshot",
              label = "Update content",
              width = "100%"
            ),
            uiOutput(outputId = "update_message_summarise_omop_snapshot")
          )
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_omop_snapshot_cdm_name",
          label = "CDM name",
          choices = choices$summarise_omop_snapshot_cdm_name,
          selected = selected$summarise_omop_snapshot_cdm_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_omop_snapshot_variable_name",
          label = "Variable name",
          choices = choices$summarise_omop_snapshot_variable_name,
          selected = selected$summarise_omop_snapshot_variable_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        position = "left"
      ),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Table Snapshot",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "summarise_omop_snapshot_table_format",
                  label = "Format",
                  choices = c("docx", "png", "pdf", "html"),
                  selected = "docx",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::downloadButton(outputId = "summarise_omop_snapshot_table_download", label = "Download table")
              ),
              class = "text-end"
            ),
            gt::gt_output("summarise_omop_snapshot_table") |>
              shinycssloaders::withSpinner()
          )
        )
      )
    )
  ),
  bslib::nav_panel(
    title = "Population Characteristics",
    icon = shiny::icon("users-gear"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        bslib::card(
          class = "sticky-top-btn",
          bslib::card_body(
            shiny::actionButton(
              inputId = "update_summarise_characteristics",
              label = "Update content",
              width = "100%"
            ),
            uiOutput(outputId = "update_message_summarise_characteristics")
          )
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_characteristics_cdm_name",
          label = "CDM name",
          choices = choices$summarise_characteristics_cdm_name,
          selected = selected$summarise_characteristics_cdm_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_characteristics_cohort_name",
          label = "Cohort name",
          choices = choices$summarise_characteristics_cohort_name,
          selected = selected$summarise_characteristics_cohort_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_characteristics_variable_name",
          label = "Variable name",
          choices = choices$summarise_characteristics_variable_name,
          selected = selected$summarise_characteristics_variable_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_characteristics_estimate_name",
          label = "Estimate name",
          choices = choices$summarise_characteristics_estimate_name,
          selected = selected$summarise_characteristics_estimate_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        position = "left"
      ),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Table Characteristics",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "summarise_characteristics_table_format",
                  label = "Format",
                  choices = c("docx", "png", "pdf", "html"),
                  selected = "docx",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::downloadButton(outputId = "summarise_characteristics_table_download", label = "Download table")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                sortable::bucket_list(
                  header = NULL,
                  sortable::add_rank_list(
                    text = "None",
                    labels = c("variable_name", "variable_level", "estimate_name"),
                    input_id = "summarise_characteristics_table_none"
                  ),
                  sortable::add_rank_list(
                    text = "Header",
                    labels = c("cdm_name", "cohort_name"),
                    input_id = "summarise_characteristics_table_header"
                  ),
                  sortable::add_rank_list(
                    text = "Group columns",
                    labels = character(),
                    input_id = "summarise_characteristics_table_group_column"
                  ),
                  sortable::add_rank_list(
                    text = "Hide",
                    labels = "table_name",
                    input_id = "summarise_characteristics_table_hide"
                  )
                ),
                position = "right"
              ),
              gt::gt_output("summarise_characteristics_table") |>
                shinycssloaders::withSpinner()
            )
          )
        ),
        bslib::nav_panel(
          title = "Plot Characteristics",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::numericInput(
                  inputId = "summarise_characteristics_plot_width",
                  label = "Width",
                  value = 15
                ),
                shiny::numericInput(
                  inputId = "summarise_characteristics_plot_height",
                  label = "Height",
                  value = 15
                ),
                shinyWidgets::pickerInput(
                  inputId = "summarise_characteristics_plot_units",
                  label = "Units",
                  choices = c("px", "cm", "inch"),
                  selected = "cm",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::numericInput(
                  inputId = "summarise_characteristics_plot_dpi",
                  label = "DPI",
                  value = 300
                ),
                shiny::downloadButton(outputId = "summarise_characteristics_plot_download", label = "Download plot")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::materialSwitch(
                  inputId = "summarise_characteristics_plot_interactive",
                  label = "Interactive",
                  value = TRUE
                ),
                shinyWidgets::pickerInput(
                  inputId = "summarise_characteristics_plot_plot_type",
                  label = "Plot type",
                  choices = c("boxplot", "barplot", "scatterplot"),
                  selected = "boxplot",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shinyWidgets::pickerInput(
                  inputId = "summarise_characteristics_plot_facet",
                  label = "Facet",
                  choices = c("cdm_name", "cohort_name"),
                  selected = "cdm_name",
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shinyWidgets::pickerInput(
                  inputId = "summarise_characteristics_plot_colour",
                  label = "Colour",
                  choices = c("cdm_name", "cohort_name"),
                  selected = "cohort_name",
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                position = "right"
              ),
              shiny::uiOutput("summarise_characteristics_plot") |>
                shinycssloaders::withSpinner()
            )
          )
        )
      )
    )
  ),
  bslib::nav_menu(
    title = "Observation Period",
    icon = shiny::icon("list"),
    bslib::nav_panel(
      title = "Observation period Summary",
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_observation_period",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_observation_period")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_observation_period_cdm_name",
            label = "CDM name",
            choices = choices$summarise_observation_period_cdm_name,
            selected = selected$summarise_observation_period_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_observation_period_observation_period_ordinal",
            label = "Observation period ordinal",
            choices = choices$summarise_observation_period_observation_period_ordinal,
            selected = selected$summarise_observation_period_observation_period_ordinal,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_observation_period_variable_name",
            label = "Variable name",
            choices = choices$summarise_observation_period_variable_name,
            selected = selected$summarise_observation_period_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_observation_period_estimate_name",
            label = "Estimate name",
            choices = choices$summarise_observation_period_estimate_name,
            selected = selected$summarise_observation_period_estimate_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Observation period",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_observation_period_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              gt::gt_output("summarise_observation_period_table") |>
                shinycssloaders::withSpinner()
            )
          ),
          bslib::nav_panel(
            title = "Plot Observation period",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_observation_period_plot_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_observation_period_plot_height",
                    label = "Height",
                    value = 15
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_plot_units",
                    label = "Units",
                    choices = c("px", "cm", "inch"),
                    selected = "cm",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::numericInput(
                    inputId = "summarise_observation_period_plot_dpi",
                    label = "DPI",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_observation_period_plot_download", label = "Download plot")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::materialSwitch(
                    inputId = "summarise_observation_period_plot_interactive",
                    label = "Interactive",
                    value = TRUE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_plot_variable",
                    label = "Variable",
                    choices = c("Number subjects", "Records per person", "Duration in days", "Days to next observation period"),
                    selected = "Number subjects",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_plot_plot_type",
                    label = "Plot type",
                    choices = c("boxplot", "barplot", "densityplot"),
                    selected = "barplot",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_plot_facet",
                    label = "Facet",
                    choices = c("cdm_name", "observation_period_ordinal"),
                    selected = "cdm_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_plot_colour",
                    label = "Colour",
                    choices = c("cdm_name", "observation_period_ordinal"),
                    selected = "observation_period_ordinal",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::uiOutput("summarise_observation_period_plot") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Table Missing Data",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_tableMissing_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_observation_period_tableMissing_download", label = "Download table")
                ),
                class = "text-end"
              ),
              gt::gt_output("summarise_observation_period_tableMissing") |>
                shinycssloaders::withSpinner()
            )
          )
        )
      )
    )
  ),
  bslib::nav_menu(
    title = "Clinical Tables",
    icon = shiny::icon("list"),
    bslib::nav_panel(
      title = "Clinical Tables Summary",
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_clinical_records",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_clinical_records")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_clinical_records_cdm_name",
            label = "CDM name",
            choices = choices$summarise_clinical_records_cdm_name,
            selected = selected$summarise_clinical_records_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_clinical_records_omop_table",
            label = "Omop table",
            choices = choices$summarise_clinical_records_omop_table,
            selected = selected$summarise_clinical_records_omop_table,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_clinical_records_variable_name",
            label = "Variable name",
            choices = choices$summarise_clinical_records_variable_name,
            selected = selected$summarise_clinical_records_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_clinical_records_estimate_name",
            label = "Estimate name",
            choices = choices$summarise_clinical_records_estimate_name,
            selected = selected$summarise_clinical_records_estimate_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Clinical records",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_clinical_records_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_clinical_records_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              gt::gt_output("summarise_clinical_records_table") |>
                shinycssloaders::withSpinner()
            )
          ),
          bslib::nav_panel(
            title = "Table Missing Data",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_clinical_records_tableMissing_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_clinical_records_tableMissing_download", label = "Download table")
                ),
                class = "text-end"
              ),
              gt::gt_output("summarise_clinical_records_tableMissing") |>
                shinycssloaders::withSpinner()
            )
          )
        )
      )
    )
  ),
  bslib::nav_panel(
    title = "Concept Counts",
    icon = shiny::icon("database"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        bslib::card(
          class = "sticky-top-btn",
          bslib::card_body(
            shiny::actionButton(
              inputId = "update_summarise_concept_id_counts",
              label = "Update content",
              width = "100%"
            ),
            uiOutput(outputId = "update_message_summarise_concept_id_counts")
          )
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_concept_id_counts_cdm_name",
          label = "CDM name",
          choices = choices$summarise_concept_id_counts_cdm_name,
          selected = selected$summarise_concept_id_counts_cdm_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_concept_id_counts_omop_table",
          label = "Omop table",
          choices = choices$summarise_concept_id_counts_omop_table,
          selected = selected$summarise_concept_id_counts_omop_table,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_concept_id_counts_estimate_name",
          label = "Estimate name",
          choices = choices$summarise_concept_id_counts_estimate_name,
          selected = selected$summarise_concept_id_counts_estimate_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        position = "left"
      ),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Table Concept Counts",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::downloadButton(outputId = "summarise_concept_id_counts_tidy_download", label = "Download csv")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::materialSwitch(
                  inputId = "summarise_concept_id_counts_tidy_interactive",
                  label = "Interactive",
                  value = TRUE
                ),
                shinyWidgets::pickerInput(
                  inputId = "summarise_concept_id_counts_tidy_display",
                  label = "Display",
                  choices = c("overall", "standard", "source", "missing standard", "missing source"),
                  selected = "overall",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                position = "right"
              ),
              reactable::reactableOutput("summarise_concept_id_counts_tidy") |>
                shinycssloaders::withSpinner()
            )
          )
        ),
        bslib::nav_panel(
          title = "Top Concept Counts",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "summarise_concept_id_counts_table_format",
                  label = "Format",
                  choices = c("docx", "png", "pdf", "html"),
                  selected = "docx",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::downloadButton(outputId = "summarise_concept_id_counts_table_download", label = "Download table")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::materialSwitch(
                  inputId = "summarise_concept_id_counts_table_interactive",
                  label = "Interactive",
                  value = TRUE
                ),
                shinyWidgets::pickerInput(
                  inputId = "summarise_concept_id_counts_table_top",
                  label = "Top",
                  choices = c(5L, 10L, 50L, 100L),
                  selected = 10L,
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                position = "right"
              ),
              shiny::uiOutput("summarise_concept_id_counts_table") |>
                shinycssloaders::withSpinner()
            )
          )
        )
      )
    )
  ),
  bslib::nav_spacer(),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("download"),
      shiny::downloadButton(
        outputId = "download_raw",
        label = "Download raw data",
        icon = shiny::icon("download")
      )
    )
  ),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("circle-info"),
      shiny::tags$img(
        src = "hds_logo.svg",
        class = "logo-img",
        alt = "Logo",
        height = "auto",
        width = "30%",
        style = "float:right"
      ),
      "This shiny app was generated with ",
      shiny::a(
        "OmopViewer",
        href = "https://github.com/OHDSI/OmopViewer",
        target = "_blank"
      ),
      shiny::strong("v0.4.0")
    )
  ),
  bslib::nav_item(bslib::input_dark_mode(id = "dark_mode", mode = "light"))
)
