name: Generate and Deploy Shiny App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    concurrency:
      group: pr-${{ github.event.pull_request.number }}
      cancel-in-progress: true

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest, r: '4.3.3'}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Install pak
        run: Rscript -e 'install.packages("pak")'

      - name: Install OmopSketch from branch
        if: github.event_name == 'pull_request'
        run: |
          BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF##*/}}
          echo "Current branch: $BRANCH_NAME"
          Rscript -e "pak::pkg_install('ohdsi/OmopSketch@$BRANCH_NAME')"

      - name: install OmopSketch from main
        if: github.event_name != 'pull_request'
        run: |
          Rscript -e 'pak::pkg_install("ohdsi/OmopSketch")'

      - name: Install extra packages
        run: Rscript extras/installExtraPackages.R

      - name: Create shiny app
        run: Rscript extras/createShiny.R

      - name: Create renv file
        run: Rscript -e 'renv::init()'
        working-directory: extras/OmopSketchShiny

      - name: Deploy to shinyapps.io
        if: github.event_name != 'pull_request'
        env:
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: Rscript extras/deployShiny.R
