on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 6 * * 1"

name: snowflake-CDMConnector

jobs:
  snowflake-CDMConnector:
    uses: ./.github/workflows/test-template.yaml
    with:
      DB_TO_TEST: snowflake-CDMConnector
      SIMPLIFIED_TEST: TRUE
    secrets:
      CDM_SNOWFLAKE_CONNECTION_STRING: ${{ secrets.CDM_SNOWFLAKE_CONNECTION_STRING }}
      CDM_SNOWFLAKE_PASSWORD: ${{ secrets.CDM_SNOWFLAKE_PASSWORD }}
      CDM_SNOWFLAKE_USER: ${{ secrets.CDM_SNOWFLAKE_USER }}
